apiVersion: v1
kind: Secret
metadata:
  name: adminapp-session
  labels:
    app: adminapp
type: Opaque
data:
  session-secret: {{ include "adminapp.resolveSecret" (dict "ctx" . "value" .Values.sessionSecret "secretName" "adminapp-session" "key" "session-secret" "length" 32) | quote }}
